import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    title: "Nike Air Monarch IV",
    star: <AiFillStar className="rating-star" />,
    reviews: "(120 reviews)",
    price: "200",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    star: <AiFillStar className="rating-star" />,
    reviews: "(50 reviews)",
    price: "200",
    company: "Nike",
    color: "red",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
    title: "Nike Waffle One Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(67 reviews)",
    price: "200",
    company: "Nike",
    color: "green",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
    title: "Adidas Running Shoe",
    star: <AiFillStar className="rating-star" />,
    reviews: "(130 reviews)",
    price: "200",
    company: "Adidas",
    color: "black",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
    title: "Flat Slip On Pumps",
    star: <AiFillStar className="rating-star" />,
    reviews: "(13 reviews)",
    price: "200",
    company: "Vans",
    color: "green",
    category: "flats",
  },
  {
    img: "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
    title: "Knit Ballet Flat",
    star: <AiFillStar className="rating-star" />,
    reviews: "(53 reviews)",
    price: "50",
    company: "Adidas",
    color: "black",
    category: "flats",
  },

  {
    img: "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
    title: "Loafer Flats",
    star: <AiFillStar className="rating-star" />,
    reviews: "(78 reviews)",
    price: "50",
    company: "Vans",
    color: "white",
    category: "flats",
  },

  {
    img: "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
    title: "Nike Zoom Freak",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "200",
    company: "Nike",
    color: "green",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
    title: "Nike Men's Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(143 reviews)",
    price: "200",
    company: "Adidas",
    color: "blue",
    category: "sneakers",
  },



  {
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "PUMA BLACK-OCE",
    star: <AiFillStar className="rating-star" />,
    reviews: "(30 reviews)",
    price: "150",
    company: "Puma",
    color: "green",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
    title: "Pacer Future Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(23 reviews)",
    price: "150",
    company: "Puma",
    color: "red",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
    title: "Unisex-Adult Super",
    star: <AiFillStar className="rating-star" />,
    reviews: "(133 reviews)",
    price: "150",
    company: "Puma",
    color: "black",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
    title: "Roma Basic Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(110 reviews)",
    price: "150",
    company: "Puma",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
    title: "Pacer Future Doubleknit",
    star: <AiFillStar className="rating-star" />,
    reviews: "(97 reviews)",
    price: "150",
    company: "Puma",
    color: "black",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "Fusion Evo Golf Shoe",
    star: <AiFillStar className="rating-star" />,
    reviews: "(87 reviews)",
    price: "100",
    company: "Puma",
    color: "green",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
    title: "Rainbow Chex Skate",
    star: <AiFillStar className="rating-star" />,
    reviews: "(142 reviews)",
    price: "100",
    company: "Vans",
    color: "red",
    category: "flats",
  },
  {
    img: "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
    title: "Low-Top Trainers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(17 reviews)",
    price: "100",
    company: "Vans",
    color: "white",
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
    title: "Vans Unisex Low-Top",
    star: <AiFillStar className="rating-star" />,
    reviews: "(144 reviews)",
    price: "100",
    company: "Vans",
    color: "blue",
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
    title: "Classic Bandana Sneakers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(88 reviews)",
    price: "50",
    company: "Nike",
    color: "black",
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
    title: "Chunky High Heel",
    star: <AiFillStar className="rating-star" />,
    reviews: "(90 reviews)",
    price: "50",
    company: "Vans",
    color: "black",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
    title: "Slip On Stiletto High Heel",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "100",
    company: "puma",
    color: "black",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
    title: "DREAM PAIRS Court Shoes",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "150",
    company: "Nike",
    color: "red",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "200",
    company: "Nike",
    color: "red",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
    title: "Low Mid Block Heels",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "200",
    company: "Nike",
    color: "black",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
    title: "Chunky High Heel",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "50",
    company: "Adidas",
    color: "black",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
    title: "Amore Fashion Stilettos",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "150",
    company: "Adidas",
    color: "white",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
    title: "Bridal Sandals Glitter",
    star: <AiFillStar className="rating-star" />,
    reviews: "(95 reviews)",
    price: "50",
    company: "Adidas",
    color: "black",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
    title: "Wedding Prom Bridal",
    star: <AiFillStar className="rating-star" />,
    reviews: "(76 reviews)",
    price: "50",
    company: "Adidas",
    color: "black",
    category: "flats",
  },
  
  {
    title: 'Nike Mens Court Royale 2 Sneaker',
    img: 'https://m.media-amazon.com/images/I/71F9NVzaN-L._AC_UL320_.jpg',
    price: '3,196',
    company: 'Nike',
    reviews: '593',
    color: 'white',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: "Nike Men's Running Shoes Air Max Excee Air Max Excee",
    img: 'https://m.media-amazon.com/images/I/711v2pPVHKL._AC_UL320_.jpg',
    price: '8,695',
    company: 'Nike',
    reviews: '298',
    color: 'black',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: "NIKE Men's Quest 6 Running Shoes",
    img: 'https://m.media-amazon.com/images/I/81JE+jwSnnL._AC_UL320_.jpg',
    price: '5,829',
    company: 'Nike',
    reviews: '39',
    color: 'black',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: 'Puma Unisex Badminton Smash Sprint Indoor Shoe',
    img: 'https://m.media-amazon.com/images/I/51xgQrBUhVL._AC_UL320_.jpg',
    price: '1,999',
    company: 'Puma',
    reviews: '600',
    color: 'white',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: 'NIKE Mens Revolution Running Shoes 7-Black/University Red-White-Fb2207-003-8Uk, 8 UK',
    img: 'https://m.media-amazon.com/images/I/719SkSU-PgL._AC_UL320_.jpg',
    price: '3,473',
    company: 'Nike',
    reviews: '55',
    color: 'black',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: 'Puma Mens Dazzler Sneaker',
    img: 'https://m.media-amazon.com/images/I/51GOpp8rAJL._AC_UL320_.jpg',
    price: '1,584',
    company: 'Puma',
    reviews: '7,003',
    color: 'black',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: 'Puma Mens Galaxis Pro Running Shoe',
    img: 'https://m.media-amazon.com/images/I/517eK2jLBQL._AC_UL320_.jpg',
    price: '3,499',
    company: 'Puma',
    reviews: '6',
    color: 'black',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: 'Nike Mens Court Vision Lo Running Shoes',
    img: 'https://m.media-amazon.com/images/I/71W8F-pZuHL._AC_UL320_.jpg',
    price: '6,598',
    company: 'Nike',
    reviews: '5',
    color: 'cream',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: "Puma Men's Coarse Running Shoe",
    img: 'https://m.media-amazon.com/images/I/51Cs+xUnFNL._AC_UL320_.jpg',
    price: '1,499',
    company: 'Puma',
    reviews: '1,015',
    color: 'black',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: 'Nike Mens M Mc Trainer 3 Running Shoes',
    img: 'https://m.media-amazon.com/images/I/71q0BqJ6PEL._AC_UL320_.jpg',
    price: '5,695',
    company: 'Nike',
    reviews: '25',
    color: 'white',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: 'Nike Mens Air Winflo 11 Air Winflo 11 Running Shoes',
    img: 'https://m.media-amazon.com/images/I/81IOFPa9aOL._AC_UL320_.jpg',
    price: '8,347',
    company: 'Nike',
    reviews: '136',
    color: 'blue',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: "NIKE Revolution 7 Men's Road Running Shoes (9) Black/White",
    img: 'https://m.media-amazon.com/images/I/81siHJuZE4L._AC_UL320_.jpg',
    price: '3,436',
    company: 'Nike',
    reviews: '91',
    color: 'black',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: 'Nike Mens Precision VII Running Shoe',
    img: 'https://m.media-amazon.com/images/I/714zVJhlT+L._AC_UL320_.jpg',
    price: '4,556',
    company: 'Nike',
    reviews: '47',
    color: 'white',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: 'adidas Mens Restound M Running Shoe',
    img: 'https://m.media-amazon.com/images/I/61z+Y7zQ7zL._AC_UL320_.jpg',
    price: '1,953',
    company: 'adidas',
    reviews: '1,033',
    color: 'black',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: 'Puma Mens Scuderia Ferrari Drift Cat 8 Shoes Sneaker',
    img: 'https://m.media-amazon.com/images/I/516--78LNXL._AC_UL320_.jpg',
    price: '3,615',
    company: 'Puma',
    reviews: '794',
    color: 'black',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: "Adidas Men's Clinch-X M Running Shoe",
    img: 'https://m.media-amazon.com/images/I/71sfbi31lhL._AC_UL320_.jpg',
    price: '1,486',
    company: 'adidas',
    reviews: '6,573',
    color: 'black',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: 'Nike Mens Flex Experience Rn 12Flex Experience Rn 12 Running Shoes',
    img: 'https://m.media-amazon.com/images/I/81RXqEFb1SL._AC_UL320_.jpg',
    price: '4,539',
    company: 'Nike',
    reviews: '169',
    color: 'brown',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: 'NIKE Mens Court Royale 2 NnSneaker',
    img: 'https://m.media-amazon.com/images/I/51T7Tytcq3L._AC_UL320_.jpg',
    price: '3,995',
    company: 'Nike',
    reviews: '2,163',
    color: 'white',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: 'adidas Mens Fluidglow M Running Shoe',
    img: 'https://m.media-amazon.com/images/I/71Ux+1L3UeL._AC_UL320_.jpg',
    price: '2,370',
    company: 'adidas',
    reviews: '2,550',
    color: 'grey',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: "Puma Men's Court Shatter Low Sneaker",
    img: 'https://m.media-amazon.com/images/I/51wBFzVxrFL._AC_UL320_.jpg',
    price: '2,399',
    company: 'Puma',
    reviews: '327',
    color: 'black',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: 'Puma Mens Softride Enzo Evo Walking Shoe',
    img: 'https://m.media-amazon.com/images/I/714RVKFlknL._AC_UL320_.jpg',
    price: '2,870',
    company: 'Puma',
    reviews: '473',
    color: 'black',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: 'NIKE Mens Full Force LoRunning Shoe',
    img: 'https://m.media-amazon.com/images/I/713C4wFx0jL._AC_UL320_.jpg',
    price: '6,796',
    company: 'Nike',
    reviews: '260',
    color: 'white',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: 'Puma Unisex Ferrari Tiburion Sneaker',
    img: 'https://m.media-amazon.com/images/I/615PmSfANKL._AC_UL320_.jpg',
    price: '3,199',
    company: 'Puma',
    reviews: '120',
    color: 'black',
    seccolor:'red',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: 'Puma Unisex SF Drift Cat 5 Ultra II Sneaker',
    img: 'https://m.media-amazon.com/images/I/71uEBGZ+5HL._AC_UL320_.jpg',
    price: '3,849',
    company: 'Puma',
    reviews: '1,097',
    color: 'black',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: 'Puma Mens Cricket Square Cricket Shoe',
    img: 'https://m.media-amazon.com/images/I/513SzEEev1L._AC_UL320_.jpg',
    price: '2,249',
    company: 'Puma',
    reviews: '479',
    color: 'white',
    seccolor:'blue',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: 'Puma Unisex Smashic Sneaker',
    img: 'https://m.media-amazon.com/images/I/51ACRzCql+L._AC_UL320_.jpg',
    price: '1,799',
    company: 'Puma',
    reviews: '1,745',
    color: 'brown',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: 'Nike Womens W Zoom Bella 6 Running Shoe',
    img: 'https://m.media-amazon.com/images/I/71jQzG00MSL._AC_UL320_.jpg',
    price: '5,022',
    company: 'Nike',
    reviews: '215',
    color: 'black',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: "Puma Men's Flyer Runner Engineer Knit Running Shoe",
    img: 'https://m.media-amazon.com/images/I/61x+X0TDyGL._AC_UL320_.jpg',
    price: '1,649',
    company: 'Puma',
    reviews: '774',
    color: 'white',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: 'adidas Mens Courun Avant M Running Shoe',
    img: 'https://m.media-amazon.com/images/I/41wZw39fRyL._AC_UL320_.jpg',
    price: '3,080',
    company: 'adidas',
    reviews: '1,090',
    color: 'grey',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: 'NIKE Mens Revolution Running Shoes 7-Black/University Red-White-Fb2207-003-9Uk, 9 UK, Multicolor',
    img: 'https://m.media-amazon.com/images/I/719SkSU-PgL._AC_UL320_.jpg',
    price: '3,473',
    company: 'Nike',
    reviews: '49',
    color: 'black',
    seccolor:'red',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: "Nike Men's Vomero 17 Running Shoes",
    img: 'https://m.media-amazon.com/images/I/51XwrKwJ6PL._AC_UL320_.jpg',
    price: '10,047',
    company: 'Nike',
    reviews: '7',
    color: 'blue',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: 'Puma Unisex-Adult X-ray 2 Square Res Sneaker',
    img: 'https://m.media-amazon.com/images/I/51QBqpS4zxL._AC_UL320_.jpg',
    price: '3,999',
    company: 'Puma',
    reviews: '2',
    color: 'white',
    seccolor:'black',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: "Puma Men's Scorch Mark Running Shoe",
    img: 'https://m.media-amazon.com/images/I/61DgMPH34bL._AC_UL320_.jpg',
    price: '1,649',
    company: 'Puma',
    reviews: '490',
    color: 'grey',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: 'Nike Mens Renew Elevate IiiRunning Shoe',
    img: 'https://m.media-amazon.com/images/I/41Ymg1p0PzL._AC_UL320_.jpg',
    price: '5,889',
    company: 'Nike',
    reviews: '171',
    color: 'white',
    seccolor:'green',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: "Puma Men's Ultimate Ease Walking Shoe",
    img: 'https://m.media-amazon.com/images/I/51UsX66AY3L._AC_UL320_.jpg',
    price: '1,714',
    company: 'Puma',
    reviews: '3,785',
    color: 'black',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: "Nike Mens Revolution 7 Men's Road Running Shoes Running Shoes",
    img: 'https://m.media-amazon.com/images/I/614pu2a28wL._AC_UL320_.jpg',
    price: '3,695',
    company: 'Nike',
    reviews: '603',
    color: 'white',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: 'adidas Mens Runally M Running Shoe',
    img: 'https://m.media-amazon.com/images/I/81ervKQ6thL._AC_UL320_.jpg',
    price: '2,860',
    company: 'adidas',
    reviews: '107',
    color: 'grey',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: 'adidas Mens Runcrypt M Running Shoe',
    img: 'https://m.media-amazon.com/images/I/71Q7q80lZ2L._AC_UL320_.jpg',
    price: '2,250',
    company: 'adidas',
    reviews: '380',
    color: 'white',
    seccolor:'red',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: 'adidas Mens Fluento M Running Shoe',
    img: 'https://m.media-amazon.com/images/I/81Vgk7MErML._AC_UL320_.jpg',
    price: '1,102',
    company: 'adidas',
    reviews: '276',
    color: 'black',
    seccolor:'green',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: 'adidas Mens Erudo M Running Shoe',
    img: 'https://m.media-amazon.com/images/I/71suXHFQb9L._AC_UL320_.jpg',
    price: '3,014',
    company: 'adidas',
    reviews: '130',
    color: 'black',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: 'adidas Mens Run Steady M Running Shoe',
    img: 'https://m.media-amazon.com/images/I/717k-AM84LL._AC_UL320_.jpg',
    price: '3,098',
    company: 'adidas',
    reviews: '556',
    color: 'black',
    seccolor:'blue',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: "Puma Womens Ivana WN's Sneaker",
    img: 'https://m.media-amazon.com/images/I/61awtv72S+L._AC_UL320_.jpg',
    price: '1,760',
    company: 'Puma',
    reviews: '771',
    color: 'red',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: 'Nike Mens Court Vision Lo Sneakers',
    img: 'https://m.media-amazon.com/images/I/51600Na7OwL._AC_UL320_.jpg',
    price: '5,695',
    company: 'Nike',
    reviews: '98',
    color: 'cream',
    seccolor:'white',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: 'Nike Mens Court Vision Lo NnRunning Shoe',
    img: 'https://m.media-amazon.com/images/I/51qAPSKkAJL._AC_UL320_.jpg',
    price: '4,995',
    company: 'Nike',
    reviews: '5,181',
    color: 'white',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: "Nike Men's Running Shoes Journey Run-Black/White-Anthracite-FN0228-001-8UK",   
    img: 'https://m.media-amazon.com/images/I/71zdGiRMewL._AC_UL320_.jpg',
    price: '8,495',
    company: 'Nike',
    reviews: '3',
    color: 'black',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: "NIKE mens Jordan Max Aura 6 Men's Shoes Running Shoes",
    img: 'https://m.media-amazon.com/images/I/71XWmB0HhyL._AC_UL320_.jpg',
    price: '100',
    company: 'Nike',
    reviews: '32',
    color: 'grey',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: 'adidas Mens Calicoz Sneaker Sneaker Shoes',
    img: 'https://m.media-amazon.com/images/I/81Mulw3RECL._AC_UL320_.jpg',
    price: '3,031',
    company: 'adidas',
    reviews: '3',
    color: 'brown',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  },
  {
    title: 'adidas Mens Axelate Walking Shoe',
    img: 'https://m.media-amazon.com/images/I/8107sz5ysFL._AC_UL320_.jpg',
    price: '1,318',
    company: 'adidas',
    reviews: '56',
    color: 'black',
    seccolor:'green',
    category: 'sneakers',
    star: <AiFillStar className="rating-star" />,
  }
];

export default data;